### ISSUE TITLE
include name of machine if job fails

### ISSUE THREAD

**Issue by PolynomialDivision** [s-schwarzmann/docker-video-encoding#3]
Currently, if a job fails u have no idea where the job was running.
Jobs that are running have the name of the vm in the machine.

Compare:
https://github.com/s-schwarzmann/docker-video-encoding/blob/master/dirjobs.py#L92
to:
https://github.com/s-schwarzmann/docker-video-encoding/blob/master/dirjobs.py#L134

I think it is a nice idea to include such information.

**Comment by csieber** [comment]
The idea was, that the job file can be just copied right back into the waiting folder after it failed. That could be ugly if the file name changes. But maybe you could add some kind of scheduling history to the job file.

**Comment by PolynomialDivision** [comment]
I understand your remark. But often u need first to debug and look for the failure and then are able to copy the stuff back.
Actually, you could accomplish the copy task using rename

    rename -v -n 's/megalomania\dx\d*.//' *.txt
Assume your VM is called megalomania. :) `-n` is dryrun...

**Comment by csieber** [comment]
Include it if it helps you! The project is basically yours now :)
